### ISSUE TITLE
Bug: SafeHandle lifetime management when owned by a ClientContext

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/Managed-OSVR#23]
The native client context object "owns" the lifetime of certain child objects, like interfaces and DisplayConfig. Currently, if you don't explicitly call Dispose of all the child objects first, before calling Dispose on the client context, you may get a native code exception either when you call Dispose on the child object or its finalizer runs for the handle object it wraps, because the native object has already been disposed of by the context.

To fix this, there may need to be some handle tracking code in the client context whenever a child object is created. This tracking would be responsible for ensuring that either those child objects are disposed explicitly before the context, or that the finalizer is suppressed on their internal handles.

**Comment by rpavlik** [comment]
Specifically, the native client context owns all child objects, because we can't generically trust the client app to properly clean up after itself.

(Basically, the context must be kept alive at least as long as the other objects, thus a reference?)

**Comment by JeroMiya** [comment]
Fixed by: https://github.com/OSVR/Managed-OSVR/issues/25
