### ISSUE TITLE
Bindings for display input APIs

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/Managed-OSVR#31]
These are part of the `DisplayConfig` API. And there's a new function to get the clipping planes for a surface.

**Comment by JeroMiya** [comment]
Work in progress here: https://github.com/JeroMiya/Managed-OSVR/tree/videoInputAPI
Just need to add code for the samples and test.

**Comment by rpavlik** [comment]
OK, core is updated and a snapshot build has made it through with the underlying functionality.

**Comment by JeroMiya** [comment]
Pull request is up:
https://github.com/OSVR/Managed-OSVR/pull/33

**Comment by JeroMiya** [comment]
Implemented in https://github.com/OSVR/Managed-OSVR/pull/33
