### ISSUE TITLE
SafeHandle and Dispose pattern for ClientContext and Interface

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/Managed-OSVR#9]
Related to this discussion:
https://github.com/OSVR/OSVR-Core/issues/130

The P/Invoke methods should be using custom SafeHandle subtypes instead of IntPtr for OSVR_ClientContext and OSVR_ClientInterface instances, and both ClientContext and Interface should implement the standard simple Dispose pattern. Currently only ClientContext is IDisposable. ClientContext.shutdown should either be removed (it's redundant) or it should just call Dispose(true) instead of the other way around.

Obstacles/Areas of research:
- SafeHandle/SafeHandleZeroOrMinusOneIsInvalid compatibility in Unity/Mono/CoreCLR? Should be present since .Net 2.0, but wouldn't hurt to check for compatibility issues across platforms.
- Are the SecurityPermission attributes necessary? Code access security was deprecated in .Net 4. They're included in the samples, but those samples are really old. Are they necessary in Unity/.Net 2 but not in .Net 4+? If so, might need to #ifdef them. I'd prefer not to run in compatibility mode in the .net 4 build if it can be helped; it may not even be an option in CoreCLR. I'm not sure.

For reference:
As for deterministic destruction/RAll in .NET, that's the Dispose pattern. This is the official documentation:
https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx
But this guide is quite a bit more comprehensive:
http://www.codeproject.com/Articles/15360/Implementing-IDisposable-and-the-Dispose-Pattern-P

I suspect a custom subclass of SafeHandle for both OSVR_ClientContext and OSVR_ClientInterface may be warranted in our case. This would simplify the IDisposable pattern for any classes that currently use IntPtr for those unmanaged types:
https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle(v=vs.100).aspx

**Comment by JeroMiya** [comment]
Experimental implementation here:
https://github.com/JeroMiya/Managed-OSVR/tree/SafeHandle_experimental

Still need to address research items and do further testing, so no pull request yet.

**Comment by JeroMiya** [comment]
Research results:
- Mono/Unity supports SafeHandles.
- Mono disables code access security by default. Since code access security is deprecated in .Net 4 and disabled by default in Mono, those attributes can be omitted.

Checkins:
- https://github.com/JeroMiya/Managed-OSVR/commit/c35081d68558c667c2b4723fab6a74bd2a029197
- https://github.com/JeroMiya/Managed-OSVR/commit/87a0f13739ef8ff7d07e9ef58c63b674484bf45f
- https://github.com/JeroMiya/Managed-OSVR/commit/97415aba772b6c4d4ca632b7a10b654f51112b5e

Next steps:
- Test in OSVR-Unity and OSVR-MonoGame.

**Comment by JeroMiya** [comment]
OK, I tested this in OSVR-Unity (Unity 5 32-bit) and OSVR-MonoGame. Looks good. Pull request incoming.

**Comment by rpavlik** [comment]
Closing as pull request was merged.
